on:  
  push:  
    branches:  
      - master  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
      - name: 'Print Working Directory'  
        run: pwd  
        
      - name: "Testing Printing"  
        run: echo youssef