on:  
  push:  
    branches:  
      - master  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
      - uses: actions/checkout@v3  
      
      - name: "login to docker hub"  
        run: echo "${{ dckr_pat_JGV1EmBq5JnKvHfpPMpBewhN5mk }}" | docker login --username youssefadl --password-stdin
